_prefs: 
  mapid: trustroots.ce8bb774
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 13.0242
  - 52.3067
  - 14
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Trustroots Hitchmap
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - road.mss
  - labels.mss
template: ''
